备份文件

diff --git a/branches/ibus/configure b/branches/ibus/configure
--- a/branches/ibus/configure
+++ b/branches/ibus/configure
@@ -599,13 +599,15 @@ PACKAGE_STRING=
 PACKAGE_BUGREPORT=
 
 ac_unique_file="configure.in"
-ac_unique_file="src/pye.cpp"
+ac_unique_file="src/main.cpp"
 ac_subst_vars='am__EXEEXT_FALSE
 am__EXEEXT_TRUE
 LTLIBOBJS
 LIBOBJS
 PACKAGE_LIBS
 PACKAGE_CFLAGS
+IBUS_LIBS
+IBUS_CFLAGS
 GLIB_LIBS
 GLIB_CFLAGS
 PKG_CONFIG
@@ -716,7 +718,9 @@ CFLAGS
 CPP
 PKG_CONFIG
 GLIB_CFLAGS
-GLIB_LIBS'
+GLIB_LIBS
+IBUS_CFLAGS
+IBUS_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1361,6 +1365,8 @@ Some influential environment variables:
   PKG_CONFIG  path to pkg-config utility
   GLIB_CFLAGS C compiler flags for GLIB, overriding pkg-config
   GLIB_LIBS   linker flags for GLIB, overriding pkg-config
+  IBUS_CFLAGS C compiler flags for IBUS, overriding pkg-config
+  IBUS_LIBS   linker flags for IBUS, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -2284,7 +2290,7 @@ fi
 
 
 # Define the identity of the package.
- PACKAGE=pye
+ PACKAGE=ibus-pye
  VERSION=0.1.0
 
 
@@ -4686,8 +4692,118 @@ else
 $as_echo "yes" >&6; }
 	:
 fi
-PACKAGE_CFLAGS="${GLIB_CFLAGS}"
-PACKAGE_LIBS="${GLIB_LIBS}"
+ibus_modules="ibus-1.0 >= 1.0.0"
+
+pkg_failed=no
+{ $as_echo "$as_me:$LINENO: checking for IBUS" >&5
+$as_echo_n "checking for IBUS... " >&6; }
+
+if test -n "$IBUS_CFLAGS"; then
+    pkg_cv_IBUS_CFLAGS="$IBUS_CFLAGS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\$ibus_modules\"") >&5
+  ($PKG_CONFIG --exists --print-errors "$ibus_modules") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_IBUS_CFLAGS=`$PKG_CONFIG --cflags "$ibus_modules" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+if test -n "$IBUS_LIBS"; then
+    pkg_cv_IBUS_LIBS="$IBUS_LIBS"
+ elif test -n "$PKG_CONFIG"; then
+    if test -n "$PKG_CONFIG" && \
+    { ($as_echo "$as_me:$LINENO: \$PKG_CONFIG --exists --print-errors \"\$ibus_modules\"") >&5
+  ($PKG_CONFIG --exists --print-errors "$ibus_modules") 2>&5
+  ac_status=$?
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; then
+  pkg_cv_IBUS_LIBS=`$PKG_CONFIG --libs "$ibus_modules" 2>/dev/null`
+else
+  pkg_failed=yes
+fi
+ else
+    pkg_failed=untried
+fi
+
+
+
+if test $pkg_failed = yes; then
+
+if $PKG_CONFIG --atleast-pkgconfig-version 0.20; then
+        _pkg_short_errors_supported=yes
+else
+        _pkg_short_errors_supported=no
+fi
+        if test $_pkg_short_errors_supported = yes; then
+	        IBUS_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors "$ibus_modules" 2>&1`
+        else
+	        IBUS_PKG_ERRORS=`$PKG_CONFIG --print-errors "$ibus_modules" 2>&1`
+        fi
+	# Put the nasty error message in config.log where it belongs
+	echo "$IBUS_PKG_ERRORS" >&5
+
+	{ { $as_echo "$as_me:$LINENO: error: Package requirements ($ibus_modules) were not met:
+
+$IBUS_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables IBUS_CFLAGS
+and IBUS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&5
+$as_echo "$as_me: error: Package requirements ($ibus_modules) were not met:
+
+$IBUS_PKG_ERRORS
+
+Consider adjusting the PKG_CONFIG_PATH environment variable if you
+installed software in a non-standard prefix.
+
+Alternatively, you may set the environment variables IBUS_CFLAGS
+and IBUS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+" >&2;}
+   { (exit 1); exit 1; }; }
+elif test $pkg_failed = untried; then
+	{ { $as_echo "$as_me:$LINENO: error: in \`$ac_pwd':" >&5
+$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
+{ { $as_echo "$as_me:$LINENO: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables IBUS_CFLAGS
+and IBUS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&5
+$as_echo "$as_me: error: The pkg-config script could not be found or is too old.  Make sure it
+is in your PATH or set the PKG_CONFIG environment variable to the full
+path to pkg-config.
+
+Alternatively, you may set the environment variables IBUS_CFLAGS
+and IBUS_LIBS to avoid the need to call pkg-config.
+See the pkg-config man page for more details.
+
+To get pkg-config, see <http://pkg-config.freedesktop.org/>.
+See \`config.log' for more details." >&2;}
+   { (exit 1); exit 1; }; }; }
+else
+	IBUS_CFLAGS=$pkg_cv_IBUS_CFLAGS
+	IBUS_LIBS=$pkg_cv_IBUS_LIBS
+        { $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+	:
+fi
+PACKAGE_CFLAGS="${GLIB_CFLAGS} ${IBUS_CFLAGS}"
+PACKAGE_LIBS="${GLIB_LIBS} ${IBUS_LIBS}"
 
 
 
